export const GLOBAL_PIPELINE = Symbol('GLOBAL_PIPELINE');
export const PIPELINE_RESOLVER = Symbol('PIPELINE_RESOLVER');
export const CLASS_PIPELINE_METADATA = Symbol('CLASS_PIPELINE_METADATA');
export const METHOD_PIPELINE_METADATA = Symbol('METHOD_PIPELINE_METADATA');
export const MODULE_PIPELINE_METADATA = Symbol('MODULE_PIPELINE_METADATA');
