export const REST_MAPPER_TOKENS = {
  CREATE_TODO: 'REST_CREATE_TODO_MAPPER',
  UPDATE_TODO: 'REST_UPDATE_TODO_MAPPER',
  DELETE_TODO: 'REST_DELETE_TODO_MAPPER',
  GET_TODO_BY_ID: 'REST_GET_TODO_BY_ID_MAPPER',
  LIST_TODOS: 'REST_LIST_TODOS_MAPPER',
} as const;
