export const GRAPHQL_MAPPER_TOKENS = {
  CREATE_TODO: 'GRAPHQL_CREATE_TODO_MAPPER',
  UPDATE_TODO: 'GRAPHQL_UPDATE_TODO_MAPPER',
  DELETE_TODO: 'GRAPHQL_DELETE_TODO_MAPPER',
  GET_TODO: 'GRAPHQL_GET_TODO_MAPPER',
  LIST_TODOS: 'GRAPHQL_LIST_TODOS_MAPPER',
} as const;
